version: "3"
services:
    bot:
        restart: always
        image: $HUB_URL:$TAG
        network_mode: "container:pia_vpn_1"
        environment:
            - NODE_ENV=production
            - LOG_LEVEL=info
            - MONGO_URL=mongodb://mongo-dev:27017/baleinebot
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - DISCORD_CHAN_ID=${DISCORD_CHAN_ID}
            - DISCORD_CMD_CHAN_ID=${DISCORD_CMD_CHAN_ID}
            - NEWBIE_ROLE=${NEWBIE_ROLE}