version: "3"
services: 
    baleine-bot:
        restart: always
        image: $HUB_URL:$TAG
        networks: 
            - backend
            - db
        environment:
            - NODE_ENV=production
            - LOG_LEVEL=info
            - MONGO_URL=mongodb://mongo-dev:27017/baleinebot
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - DISCORD_CHAN_ID=${DISCORD_CHAN_ID}
            - DISCORD_CMD_CHAN_ID=${DISCORD_CMD_CHAN_ID}

networks:
    backend:
        external: true
    db:
        external: true